[common] Mograte from universal variables to global (fish)

diff --git a/common b/common
--- a/common
+++ b/common
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-export COMMON_VERSION='2.10'
+export COMMON_VERSION='2.11'
 
 
 ## Colors
@@ -794,16 +794,47 @@ env_set_permanent() {
     local result_code=0
     local result_msg=''
 
+    if ! [[ $var_name =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]]; then
+        printf '\n'
+        return 1
+    fi
+
     # fish
     if is_command_available 'fish'; then
         ((result_code += 1))
-        # Set fish universal variable:
-        # shared across all fish sessions, persists after reboot
-        if fish -c "set -Ux $var_name '$var_value'" &>> "$LOG_FILE"; then
-            ((result_code -= 1))
-            # Append fish to the current result msg
-            [ -z "$result_msg" ] && result_msg='fish' || result_msg="${result_msg},fish"
+
+        local fish_conf_dir="${XDG_CONFIG_HOME:-$HOME/.config}/fish/conf.d"
+        local fish_env_file="${fish_conf_dir}/anarchy-env-${var_name}.fish"
+        local fish_env_tmpfile=''
+        local escaped_value
+
+        # TODO: temporary hack to clean up previously set universal variables
+        #       remove in the future versions.
+
+        # Serialize with fish itself so arbitrary values remain valid fish syntax
+        # shellcheck disable=SC2016  # $value is expanded by fish
+        if escaped_value=$(printf '%s' "$var_value" | fish --no-config -c '
+                read --null value
+                string escape -- "$value"
+            ' 2>> "$LOG_FILE") &&
+           mkdir -p "$fish_conf_dir" &>> "$LOG_FILE" &&
+           fish_env_tmpfile=$(mktemp "${fish_env_file}.XXXXXX" 2>> "$LOG_FILE") &&
+           printf '# Managed by Anarchy; generated by env_set_permanent\nset -gx -- %s %s\n' \
+               "$var_name" "$escaped_value" > "$fish_env_tmpfile" 2>> "$LOG_FILE" &&
+           mv -f "$fish_env_tmpfile" "$fish_env_file" &>> "$LOG_FILE"; then
+            # Erase the old universal only after its replacement exists
+            # shellcheck disable=SC2016  # $argv is expanded by fish
+            if fish -c '
+                if set --query --universal $argv[1]
+                    set --erase --universal $argv[1]; or exit 1
+                end
+            ' -- "$var_name" &>> "$LOG_FILE"; then
+                ((result_code -= 1))
+                # Append fish to the current result msg
+                [ -z "$result_msg" ] && result_msg='fish' || result_msg="${result_msg},fish"
+            fi
         fi
+        [ -n "$fish_env_tmpfile" ] && rm -f "$fish_env_tmpfile"
     fi
 
     # bash
@@ -847,19 +878,28 @@ env_unset_permanent() {
     local result_code=0
     local result_msg=''
 
+    if ! [[ $var_name =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]]; then
+        printf '\n'
+        return 1
+    fi
+
     # fish
     if is_command_available 'fish'; then
-        # Erase fish universal variable:
-        if fish -c "set -q $var_name" &>> "$LOG_FILE"; then
-            ((result_code += 1))
-            # Removes the variable from all fish sessions
-            if fish -c "set -Ue $var_name" &>> "$LOG_FILE"; then
-                ((result_code -= 1))
-                # Append fish to the current result msg
-                [ -z "$result_msg" ] && result_msg='fish' || result_msg="${result_msg},fish"
-            fi
-        else
-            # Absence of the variable is also a successful result
+        ((result_code += 1))
+
+        local fish_conf_dir="${XDG_CONFIG_HOME:-$HOME/.config}/fish/conf.d"
+        local fish_env_file="${fish_conf_dir}/anarchy-env-${var_name}.fish"
+
+        # Remove both the managed file and state left by older common versions
+        # shellcheck disable=SC2016  # $argv is expanded by fish
+        if fish -c '
+                if set --query --universal $argv[1]
+                    set --erase --universal $argv[1]; or exit 1
+                end
+            ' -- "$var_name" &>> "$LOG_FILE" &&
+           rm -f "$fish_env_file" &>> "$LOG_FILE"; then
+            ((result_code -= 1))
+            # Append fish to the current result msg
             [ -z "$result_msg" ] && result_msg='fish' || result_msg="${result_msg},fish"
         fi
     fi
